# Generated by Django 3.2.12 on 2022-03-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220205_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Middle name'),
        ),
    ]
