# Generated by Django 3.2 on 2022-02-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('second_name', models.CharField(max_length=150, verbose_name='Second name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Middle name')),
                ('avatar', models.ImageField(default='/home/whoman/dev/other/AutoMasterAPI/default/master_avatar.png', upload_to='', verbose_name='Avatar image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
