# Generated by Django 3.2 on 2022-02-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='avatar',
            field=models.ImageField(blank=True, default='/home/whoman/dev/other/AutoMasterAPI/default/master_avatar.png', upload_to='', verbose_name='Avatar image'),
        ),
    ]
