# Generated by Django 3.2 on 2022-02-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_master_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='avatar',
            field=models.ImageField(blank=True, default='/usr/src/app/default/master_avatar.png', upload_to='', verbose_name='Avatar image'),
        ),
    ]
