# Generated by Django 3.2 on 2022-02-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='register',
            unique_together={('master', 'start_at')},
        ),
    ]
