# Generated by Django 3.2 on 2022-02-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_auto_20220206_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='end_at',
            field=models.DateTimeField(null=True),
        ),
    ]
