# Generated by Django 3.2 on 2022-02-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_alter_register_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='end_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
